# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging Settings (SLF4J/Logback will pick these up)
logging.file.name=./data/spring.log
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# resliency-4j config for retry
resilience4j.retry.instances.exchangeRatesApi.max-attempts=3
resilience4j.retry.instances.exchangeRatesApi.wait-duration=2s
resilience4j.retry.instances.exchangeRatesApi.enable-exponential-backoff=true
resilience4j.retry.instances.exchangeRatesApi.exponential-backoff-multiplier=2

# Retry on network/timeout issues.
resilience4j.retry.instances.exchangeRatesApi.retry-exceptions=org.springframework.web.client.ResourceAccessException,java.util.concurrent.TimeoutException,org.springframework.web.client.HttpServerErrorException

# Limits how many times we call the Exchange Rates API to avoid rate limits
resilience4j.ratelimiter.instances.exchangeRatesLimit.limit-for-period=10
resilience4j.ratelimiter.instances.exchangeRatesLimit.limit-refresh-period=60s
resilience4j.ratelimiter.instances.exchangeRatesLimit.timeout-duration=0s

# Circuit breaker config
# Name must match the annotation: @CircuitBreaker(name = "exchangeRatesCircuit")
resilience4j.circuitbreaker.instances.exchangeRatesCircuit.register-health-indicator=true
resilience4j.circuitbreaker.instances.exchangeRatesCircuit.sliding-window-size=10
resilience4j.circuitbreaker.instances.exchangeRatesCircuit.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.exchangeRatesCircuit.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.exchangeRatesCircuit.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.exchangeRatesCircuit.sliding-window-type=COUNT_BASED

# Link it to the same exceptions as Retry
resilience4j.circuitbreaker.instances.exchangeRatesCircuit.record-exceptions=org.springframework.web.client.ResourceAccessException,java.util.concurrent.TimeoutException,org.springframework.web.client.HttpServerErrorException