# Database Configuration

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASS}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.root=WARN
logging.level.com.sk.ledger=INFO